version: '3.8'
services:
  bpf-loader:
    build: .
    image: bpf-example
    privileged: true
    volumes:
      - ./work:/work
      - /sys/kernel/debug:/sys/kernel/debug
    command: /work/entrypoint.sh